"""add_priority_and_owner_to_tasks

Revision ID: 851b3a465574
Revises: 0001_initial_schema
Create Date: 2026-04-24 22:45:54.448479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '851b3a465574'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=True))
    
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_owner_id_users', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('priority')
    # ### end Alembic commands ###
