"""add user name

Revision ID: 87a58fcc86e5
Revises: 851b3a465574
Create Date: 2026-04-24 23:32:37.734069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87a58fcc86e5'
down_revision: Union[str, Sequence[str], None] = '851b3a465574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
